#if !canImport(ObjectiveC)
import XCTest

extension GETTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GETTests = [
        ("testChain", testChain),
        ("testObjectBody", testObjectBody),
        ("testTextBody", testTextBody),
    ]
}

extension POSTTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__POSTTests = [
        ("testObjectBody", testObjectBody),
        ("testTextBody", testTextBody),
    ]
}

extension RouterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouterTests = [
        ("testMixedMethods", testMixedMethods),
        ("testMixedMethodsInGroup", testMixedMethodsInGroup),
        ("testMultipleParams", testMultipleParams),
        ("testRoot", testRoot),
        ("testStaticRoutes", testStaticRoutes),
        ("testSubPaths", testSubPaths),
        ("testVariablePaths", testVariablePaths),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GETTests.__allTests__GETTests),
        testCase(POSTTests.__allTests__POSTTests),
        testCase(RouterTests.__allTests__RouterTests),
    ]
}
#endif
